---
author: "Jeremias Endrina"
date: "10/31/2021"
---

In this project, we were tasked to create predictive models and automate markdown reports on 6 different news channels. We read-in an online [news popularity data set]("https://archive.ics.uci.edu/ml/datasets/Online+News+Popularity"), did exploratory data analysis and generated four candidate predictive models namely: 2 linear regressions, 1 random forest and 1 boosted tree. We then compared the performance of these four models using their respective RMSE and declared a winner. We performed all these steps across different news channel.  

As I mentioned in my Project 1 blog, one thing that I would do differently is to work on the project as early as possible which I did here in Project 2. This strategy helped me resolve issues that arise along the way as quick and timely as possible. I had enough time to write my part of the code and review them before my partner and I finalized our output.  

My partner and I never had any difficulties because despite our busy schedule, we were able to communicate effectively and make adjustments efficiently. Both of us were open to any ideas that we thought can improve our project.  

My big take-aways from this project are the lessons I gained from automating results, realizing how powerful caret package is in machine learning and recognizing that being open and professional contribute a lot to the success of this project. Automating output makes task easy to do while achieving the same results as expected. With the help of the caret package, everything worked smoothly from splitting data to training and test sets to comparing results of model performance using RMSE. Lastly, I am lucky to have a partner who is not just a pro in R but at the same time very professional.  

I am proud to share the results of our project. Below are the links to our Project 2 Repo and github page.  

[github repo]("https://github.com/jerryendrina/ST558-Project2")  

[Project 2 Webpage]("https://jerryendrina.github.io/ST558-Project2/")  

