---
author: "Jeremias Endrina"
date: "11/28/2021"
---

After learning a lot from this class, my initial thoughts and definitions of
what a data scientist is and what they do have never been changed. In fact, this course has reinforced more what I know about them and what they do in the 
real world. I still think that being a data scientist is about having the ability to do statistical analysis, programming and having strong knowledge of the domain where the data scientist is applying his or her self.

Since programming has become a crucial part of being a data scientist, learning
different languages are vital for someone's success in the field. This semester,
I am glad that I am able to take classes on both R and Python for Data Science.
I have my own share of difficulties while learning both languages but in the end I am grateful that I can finally say I am ready to face the world of data science. Going forward, I will continue to learn more functions on R and
Python to better my skills as a future data scientist.

One thing that I would do differently in practice is to always refer to documentations to understand how functions work and to make use of the open source
codes for they are always readily available to get things started when I feel like
having no idea on what to do. 

I am very grateful to my professor, Dr. Post, for all the help that he extended 
to me to be successful in this course. =)