---
author: "Jeremias Endrina"
date: "10/3/2021"
---

## Project 1 Background

In this project, I was tasked to create a vignette that demonstrates how to access data from an API particularly [Covid-19 API](https://covid19api.com/). I showcased different packages and functions to manipulate generated data set, apply exploratory analysis and present results using tables and plots. The vignette focused on comparing the Philippines' Covid-19 data to that of the neighboring countries with similar land area, demographics and population.

Doing this project gave me mixed emotions. I enjoyed making the vignette because the idea of working on real-time data and sharing real-time analysis thrilled me big time. I find the whole process so cool and relevant especially during this pandemic. But at the same it made me sad knowing that my home country, the Philippines, is lagging behind in terms of its effort of controlling the spread of the virus and minimizing unnecessary loss of lives. On the brighter side, this project gives me hope that there are ways to improve the fight against this virus. One thing that the government can do is to look at, learn from and imitate neighboring countries’ strategies that work to mitigate the spread of the virus. The fight is not over yet as long as we are willing to learn from our mistakes and do our part.

The most difficult part for me was figuring out the reason why my code doesn't knit 100% when no error is made upon running each chunk. I tried to trace where the issue is and I realized that some data sets did not generate completely because it already reached the maximum number of queries. I was forced to limit the number of countries to compare. Although the issue can be addressed if I subscribe to the API's website. 

Also, it did take me awhile to complete the project. One thing I would do differently next time is to start working as early as possible and try to plan out the goal and steps to avoid wasting time on the process.


Below are the links to my github repo and the repo itself:  

[my github repo](https://github.com/jerryendrina/Covid-19-API-Vignette)  

[covid 19 API Vignette](https://jerryendrina.github.io/Covid-19-API-Vignette/)  



